"""hw4:Revise homework 3 to make it PEP8 compliant."""

def test_dataframe(df, name_list):
    """test hw3 dataframe:input dataframe generated by pandas and dataframe columns' name list.
        output whether the df fits in."""
    if df.columns.tolist() != name_list:
        return False

    for i in range(len(df.columns.values.tolist())):
        test_col = df[df.columns.values.tolist()[i]]
        length = len(test_col)
        for j in range(length):
            if isinstance(test_col[j], test_col[0]):
                return False

    if df.shape[0] < 10:
        return False
    return True

def test_column_type(df):
    """test column type: input dataframe generated by pandas.
        output whether the every value in columns is the correct type"""
    for i in range(len(df.columns.values.tolist())):
        test_col = df[df.columns.values.tolist()[i]]
        length = len(test_col)
        for j in range(length):
            if isinstance(test_col[j], test_col[0]):
                return False
    return True

def test_nan_value(df):
    """test nan value: input dataframe generated by pandas.
        output whether there are null values."""
    for isnan in df.isnull().any().tolist():
        if isnan:
            return True
    return False

def test_one_row(df):
    """test more than one row: input dataframe generated by pandas.
        output whether the dataframe has more. than one rows."""
    return df.shape[0] >= 1
